data:
  dataset: cifar10
  data_dir: "./data"
  batch_size: 128
  num_workers: 4

model:
  in_channels: 3
  num_classes: 10
  num_nodes: 4
  num_cells: 3
  num_partial_channel_connections: 4
  edge_norm_init: 1.0
  edge_norm_strength: 1.0
  num_segments: 4

training:
  max_epochs: 1 # 50
  momentum: 0.9
  learning_rate: 0.025
  arch_learning_rate: 0.001
  edge_norm_learning_rate: 0.001
  weight_decay: 0.0003
  arch_weight_decay: 0.001
  edge_norm_weight_decay: 0.001
  derived_epochs: 1 # 100
  drop_path_prob_start: 0.0
  drop_path_prob_end: 0.3

logging:
  log_dir: "logs/"
  experiment_name: "pc_darts"
